### ISSUE TITLE
[BUG] Carousel component can't contain dynamic data list

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/open-app-builder#2489]
**Describe the bug**
The carousel component can render content form a `begin_items` `end_items` loop, but not from a `begin_data_items` `end_data_items`. 

**App version**
v0.16.36

**Deployment Sheet(s)**
Want to use this structure in the PLH Kids TZ deployment in the Resource Centre ([activity_carousel](https://docs.google.com/spreadsheets/d/1BoC8Zide9G0WNwqkVA2VYAEsE47kSUrBeFUJ8TJI7f0/edit?gid=1139990492#gid=1139990492)) and in the Library ([lib_books](https://docs.google.com/spreadsheets/d/1Jt_JwuTkbSC79WXNhUjgPUFiewdRwRSKUvkZuUxwU3w/edit?gid=1491860017#gid=1491860017)).

When using dynamic data for this, we can immediately store the "favourite" and "accessed timestamps" on the relevant row of the dynamic data list.

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/52a8b36b-6556-45d1-8026-23228f95d11b)

**Comment by jfmcquade** [comment]
@chrismclarke, you've been looking at code in this area a lot recently, do you have an idea of how difficult this would be to fix?

As I understand it, this issue is due to the fact that rows within a standard `items` loop are processed at the template row level and are rendered at the same level as standard template rows in a sense, whereas rows within a `data-items` loop are further processed by a specific `data-items` component and are rendered inside a container associated with that component. The carousel logic is such that it renders a new "slide" for each of its child rows, and in the case of a `data-items` loop, the immediate child is the data items component itself, so the whole container gets put in a single slide. 

The same issue, where the `data-items` loop can't be used to render a list of component-specific elements, would apply to other components that loop over their child rows to render each one in a certain way (e.g. `accordion`, `display-group`, `animated-slides` etc.), I think we just haven't encountered these use cases yet. 

For that reason I think a fix would ideally involve a change at the `data-items` level rather than at the level of these parent components. However, I'm not sure how we could rework the `data-items` component to add its children to the DOM in a way that didn't wrap them in a single parent component element.

**Comment by esmeetewinkel** [comment]
Same holds for `display_grid` component (works for `items` but with `data_items` it just shows the items in a single column).

![image](https://github.com/user-attachments/assets/1458711d-e602-4c7b-9def-9febf4076159)

**Comment by chrismclarke** [comment]
Thanks @jfmcquade and @esmeetewinkel for the insights

**Problem Statement**
Taking a closer look there appears to be a fundamental incompatibility. When using a component that renders `items` within its child rows, the `items` list can run a single time and replace itself with the output of the generated list, meaning from the parent component point of view there's just a list of child rows inside.

When using `data_items` however a top-level component needs to be rendered which handles subscribing to any data changes and rendering generated rows as a child of itself. It can't replace itself as that would lose the live data subscriptions which it is intended for.

**Proposed Solution**
This could likely be fixed in one of two ways, either:

1. All components that render data_items child rows be refactored to explicitly receive the list of rows to render as a parameter list, and have their own logic that supports subscribing to data and rendering the generated rows as required. Downsides to this approach would be that the templating logic for items vs data_items would look different, and it wouldn't be clear how the rows should be rendered if a combination of static child rows and generated items rows were included.

2. The main template container is updated to handle all data subscriptions, injecting generated rows into components as required. The downside to this would likely be a larger refactor. 

Both solutions necessitate decoupling the logic used to generate data_items loops from the component currently used to display them, so I'll plan to start work on that first and see where things get to. But I'd suggest that this might take a bit of time to do, so it would be good to identify what components are the highest priority to add workarounds for (if required)
